databases:
  - name: Mydea_DB
    databaseName: mydea_db
    user: Mydea
    region: singapore

services:
  - type: web
    name: Mydea
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Mydea
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false